import tailwindColor from 'tailwindcss/colors';

export const Color = {
    primary: '#643fdb',
    secondary: '#ff8a00',
    success: '#198754',
    warn: '#ffc107',
    danger: '#dc3545',
    info: '#0dcaf0',
    inherit: tailwindColor.inherit,
    current: tailwindColor.current,
    transparent: tailwindColor.transparent,
    black: tailwindColor.black,
    white: tailwindColor.white,
    slate: tailwindColor.slate,
    gray: tailwindColor.gray,
    zinc: tailwindColor.zinc,
    neutral: tailwindColor.neutral,
    stone: tailwindColor.stone,
    red: tailwindColor.red,
    orange: tailwindColor.orange,
    amber: tailwindColor.amber,
    yellow: tailwindColor.yellow,
    lime: tailwindColor.lime,
    green: tailwindColor.green,
    emerald: tailwindColor.emerald,
    teal: tailwindColor.teal,
    cyan: tailwindColor.cyan,
    sky: tailwindColor.sky,
    blue: tailwindColor.blue,
    indigo: tailwindColor.indigo,
    violet: tailwindColor.violet,
    purple: tailwindColor.purple,
    fuchsia: tailwindColor.fuchsia,
    pink: tailwindColor.pink,
    rose: tailwindColor.rose,
};
